# Generated by Django 2.2.6 on 2019-10-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyecare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='regis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
    ]
